name: Deploy Workflow
on: push
env:
  API_KEY: ${{ secrets.VITE_API_KEY }}

jobs:
  deploy:
    runs-on: windows-latest
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Mostrar API_KEY
        run: echo $env:VITE_API_KEY
